[package]
name = "complex-numworks"
version = "0.1.0"
authors = ["NumWorks <contact@numworks.com>"]
edition = "2018"

[profile.release]
lto = "fat"
opt-level = 3
strip = "symbols"
panic = "abort"

[dependencies]
heapless = "0.8.0"
libm = "0.2.8"
