[tasks.build]
command = "cargo"
args = ["build", "--release"]

[tasks.run]
command = "cargo"
args = ["run", "--release"]

[tasks.pack]
dependencies = ["build"]
command = "cp"
args = ["target/thumbv7em-none-eabihf/release/epsilon-sample-app", "build/app.nwa"]
